In [1]:
import pandas as pd
import numpy as np
import requests
import io
import pdfplumber

In [2]:
url = 'https://data.lacity.org/api/views/2nrs-mtv8'
response = requests.get(url)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns',None)
if response.status_code == 200:
    data = response.json()['columns']
    df = pd.DataFrame(data)[['name','dataTypeName','description']]
    display(df.style.set_properties(**{'text-align': 'left'}))
else:
    print(f'Error: {response.status_code}')

In [3]:
url = 'https://data.lacity.org/api/views/2nrs-mtv8/rows.csv?accessType=DOWNLOAD'
response = requests.get(url, stream=True)
if response.status_code == 200:
    print(response.status_code)
    print(f"Content-Type: {response.headers.get('Content-Type')}")
else:
    print(f'Error: {response.status_code}')

200
Content-Type: text/csv; charset=utf-8

In [4]:
crime = pd.read_csv(io.StringIO(response.text))

In [5]:
crime

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,Vict Age,Vict Sex,Vict Descent,Premis Cd,Premis Desc,Weapon Used Cd,Weapon Desc,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,211507896,04/11/2021 12:00:00 AM,11/07/2020 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,0377,31,M,H,501.0,SINGLE FAMILY DWELLING,NaN,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,NaN,34.2124,-118.4092
1,201516622,10/21/2020 12:00:00 AM,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",0416 0334 2004 1822 1414 0305 0319 0400,32,M,H,102.0,SIDEWALK,200.0,KNIFE WITH BLADE 6INCHES OR LESS,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203
2,240913563,12/10/2024 12:00:00 AM,10/30/2020 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,0377,30,M,W,501.0,SINGLE FAMILY DWELLING,NaN,NaN,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509
3,210704711,12/24/2020 12:00:00 AM,12/24/2020 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER),0344,47,F,A,101.0,STREET,NaN,NaN,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747
4,201418201,10/03/2020 12:00:00 AM,09/29/2020 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),1300 0344 1606 2032,63,M,H,103.0,ALLEY,NaN,NaN,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004889,240710284,07/24/2024 12:00:00 AM,07/23/2024 12:00:00 AM,1400,7,Wilshire,788,1,510,VEHICLE - STOLEN,NaN,0,NaN,NaN,101.0,STREET,NaN,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,4000 W 23RD ST,NaN,34.0362,-118.3284
1004890,240104953,01/15/2024 12:00:00 AM,01/15/2024 12:00:00 AM,100,1,Central,101,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0329 0400 0416,0,X,X,503.0,HOTEL,500.0,UNKNOWN WEAPON/OTHER WEAPON,IC,Invest Cont,745.0,NaN,NaN,NaN,1300 W SUNSET BL,NaN,34.0685,-118.2460
1004891,240410786,10/14/2024 12:00:00 AM,10/11/2024 12:00:00 AM,2330,4,Hollenbeck,421,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD",0344,29,M,B,210.0,RESTAURANT/FAST FOOD,NaN,NaN,IC,Invest Cont,341.0,NaN,NaN,NaN,1700 ALBION ST,NaN,34.0675,-118.2240
1004892,240309674,04/24/2024 12:00:00 AM,04/24/2024 12:00:00 AM,1500,3,Southwest,358,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1822 0334 0416 0445 0449 1202,70,F,W,102.0,SIDEWALK,308.0,STICK,IC,Invest Cont,230.0,NaN,NaN,NaN,FLOWER ST,JEFFERSON BL,34.0215,-118.2868
1004893,240910892,08/13/2024 12:00:00 AM,08/12/2024 12:00:00 AM,2300,9,Van Nuys,914,1,510,VEHICLE - STOLEN,NaN,0,NaN,NaN,108.0,PARKING LOT,NaN,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,6900 VESPER AV,NaN,34.1961,-118.4510

In [6]:
crime.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004894 entries, 0 to 1004893
Data columns (total 28 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   DR_NO           1004894 non-null  int64
 1   Date Rptd       1004894 non-null  object
 2   DATE OCC        1004894 non-null  object
 3   TIME OCC        1004894 non-null  int64
 4   AREA            1004894 non-null  int64
 5   AREA NAME       1004894 non-null  object
 6   Rpt Dist No     1004894 non-null  int64
 7   Part 1-2        1004894 non-null  int64
 8   Crm Cd          1004894 non-null  int64
 9   Crm Cd Desc     1004894 non-null  object
 10  Mocodes         853296 non-null   object
 11  Vict Age        1004894 non-null  int64
 12  Vict Sex        860263 non-null   object
 13  Vict Descent    860251 non-null   object
 14  Premis Cd       1004878 non-null  float64
 15  Premis Desc     1004306 non-null  object
 16  Weapon Used Cd  327216 non-null   float64
 17  Weapon Desc     327216 non-null   object
 18  Status          1004893 non-null  object
 19  Status Desc     1004894 non-null  object
 20  Crm Cd 1        1004883 non-null  float64
 21  Crm Cd 2        69154 non-null    float64
 22  Crm Cd 3        2314 non-null     float64
 23  Crm Cd 4        64 non-null       float64
 24  LOCATION        1004894 non-null  object
 25  Cross Street    154228 non-null   object
 26  LAT             1004894 non-null  float64
 27  LON             1004894 non-null  float64
dtypes: float64(8), int64(7), object(13)
memory usage: 948.3 MB

In [7]:
crime.isnull().sum()

DR_NO                   0
Date Rptd               0
DATE OCC                0
TIME OCC                0
AREA                    0
AREA NAME               0
Rpt Dist No             0
Part 1-2                0
Crm Cd                  0
Crm Cd Desc             0
Mocodes            151598
Vict Age                0
Vict Sex           144631
Vict Descent       144643
Premis Cd              16
Premis Desc           588
Weapon Used Cd     677678
Weapon Desc        677678
Status                  1
Status Desc             0
Crm Cd 1               11
Crm Cd 2           935740
Crm Cd 3          1002580
Crm Cd 4          1004830
LOCATION                0
Cross Street       850666
LAT                     0
LON                     0
dtype: int64

In [8]:
url = 'https://data.lacity.org/api/views/2nrs-mtv8/files/4591b6bf-5846-4de0-9fb0-8780a77a036c?download=true&filename=MO_CODES_Numerical_20191119.pdf'
response = requests.get(url)
response.status_code

200

In [9]:
# Translating the Mocodes from their code to their description according to LAPD, 
# The descroption is in PDF file so the information is extracted according to the files structure 
mocodes = {}
for page in pdfplumber.open(io.BytesIO(response.content)).pages:
    pg = page.extract_text()
    pg = pg.split('\n')[3:-1]
    for code in pg:
        mocodes[code[:4]] = code[5:]
crime['Mocodes'] = crime['Mocodes'].fillna('').str.split()

def process_mo_row(code_list):
    if not isinstance(code_list, list):
        return "Unknown"
    if len(code_list) == 0:
        return "Unknown"
    descriptions = [mocodes.get(str(code), "Code Not Found") for code in code_list]
    return ", ".join(descriptions)


crime['Mocode Text'] = crime['Mocodes'].apply(process_mo_row)

In [10]:
# Check that one or more columns in Crm Cd 1 to 4 can be filled simultaneously
severity_cols = ['Crm Cd 1', 'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4']
crime_counts = crime[severity_cols].notna().sum(axis=1)
multi_crime_mask = crime_counts > 1
overlap_df = crime[multi_crime_mask]
print(f"Total rows with more than one Crime Code: {len(overlap_df)}")
if not overlap_df.empty:
    display(overlap_df[severity_cols].info())

Total rows with more than one Crime Code: 69143
<class 'pandas.core.frame.DataFrame'>
Int64Index: 69143 entries, 7 to 1004876
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Crm Cd 1  69143 non-null  float64
 1   Crm Cd 2  69143 non-null  float64
 2   Crm Cd 3  2314 non-null   float64
 3   Crm Cd 4  64 non-null     float64
dtypes: float64(4)
memory usage: 2.6 MB

None

In [11]:
# We will create a column to rank the severity of the crimes based on the columns description and structure logic
#1) map the part 1-2 to flip them (2 is more severe)

#2) for every column Crm Cd 1 to 4 if the value is not null i will replace with prime numbers that are linearly independent, In this case I chose, Crm 1 :11, crm 2: 7, crm 3: 3, crm 4: 2

#3) sum the 4 columns together (if there is a combination it will have a higher score) and multiply by the mapped (part 1-2) column

In [12]:
crm1 = np.where(crime['Crm Cd 1'].isnull(),0,11)
crm2 = np.where(crime['Crm Cd 2'].isnull(),0,7)
crm3 = np.where(crime['Crm Cd 3'].isnull(),0,3)
crm4 = np.where(crime['Crm Cd 4'].isnull(),0,2)
part21 = crime['Part 1-2'].map({1: 2, 2: 1}).fillna(1)
sev_score = part21*(crm1 + crm2 + crm3 + crm4)

unique_sev_scores = sorted(sev_score.unique())
for i in range(len(unique_sev_scores)):
    sev_score.replace(unique_sev_scores[i],i+1,inplace=True)

crime['Severity Score'] = sev_score

In [13]:
# Change the date reported and date occured to the format DD/MM/YYYY
crime['Date Rptd'] = pd.to_datetime(crime['Date Rptd'])
crime['Date_Reported'] = crime['Date Rptd'].dt.strftime('%d/%m/%Y')

crime['DATE OCC'] = pd.to_datetime(crime['DATE OCC'])
crime['Date_Occured'] = crime['DATE OCC'].dt.strftime('%d/%m/%Y')

In [14]:
# Fix the Time of Occurrance column
crime['TIME OCC'] = crime['TIME OCC'].astype(str).str.zfill(4)

In [15]:
# Map the victim descent column to their corresponding description
ethnicity = {'A': 'Other Asian', 'B':'Black', 'C':'Chinese','D':'Cambodian','F':'Filipino', 'G':'Guamanian',
             'H':'Hispanic/Latin/Mexican','I':'American Indian/Alaskan Native','J':'Japanese' ,'K':'Korean','L':'Laotian',
             'O':'Other', 'P':'Pacific Islander','S':'Samoan', 'U':'Hawaiian','V':'Vietnamese','W':'White','X':'Unknown','Z':'Asian Indian'}
crime['Vict Descent'] = crime['Vict Descent'].map(ethnicity)

In [18]:
# Rearrange the columns while getting rid of the ones who dont provide information we can analyze
crime = crime[['DR_NO','Date_Occured','TIME OCC','Date_Reported','Crm Cd Desc','Weapon Desc','Mocode Text','Severity Score','Vict Sex','Vict Age',
      'Vict Descent','AREA NAME', 'LOCATION', 'Cross Street','Premis Desc','LAT','LON']]
crime

,DR_NO,Date_Occured,TIME OCC,Date_Reported,Crm Cd Desc,Weapon Desc,Mocode Text,Severity Score,Vict Sex,Vict Age,Vict Descent,AREA NAME,LOCATION,Cross Street,Premis Desc,LAT,LON
0,211507896,07/11/2020,0845,11/04/2021,THEFT OF IDENTITY,NaN,Takes vict's identification/driver license,2,M,31,Hispanic/Latin/Mexican,N Hollywood,7800 BEEMAN AV,NaN,SINGLE FAMILY DWELLING,34.2124,-118.4092
1,201516622,18/10/2020,1845,21/10/2020,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",KNIFE WITH BLADE 6INCHES OR LESS,"Hit-Hit w/ weapon, Brandishes weapon, Suspect is homeless/transient, Stranger, Photographs, Attacks from rear, Profanity Used, Force used",6,M,32,Hispanic/Latin/Mexican,N Hollywood,ATOLL AV,N GAULT,SIDEWALK,34.1993,-118.4203
2,240913563,30/10/2020,1240,10/12/2024,THEFT OF IDENTITY,NaN,Takes vict's identification/driver license,2,M,30,White,Van Nuys,14600 SYLVAN ST,NaN,SINGLE FAMILY DWELLING,34.1847,-118.4509
3,210704711,24/12/2020,1310,24/12/2020,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER),NaN,Removes vict property,6,F,47,Other Asian,Wilshire,6000 COMEY AV,NaN,STREET,34.0339,-118.3747
4,201418201,29/09/2020,1830,03/10/2020,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),NaN,"Vehicle involved, Removes vict property, Open/unlocked, Victim left property unattended",6,M,63,Hispanic/Latin/Mexican,Pacific,4700 LA VILLA MARINA,NaN,ALLEY,33.9813,-118.4350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004889,240710284,23/07/2024,1400,24/07/2024,VEHICLE - STOLEN,NaN,Unknown,6,NaN,0,NaN,Wilshire,4000 W 23RD ST,NaN,STREET,34.0362,-118.3284
1004890,240104953,15/01/2024,0100,15/01/2024,VANDALISM - MISDEAMEANOR ($399 OR UNDER),UNKNOWN WEAPON/OTHER WEAPON,"Vandalized, Force used, Hit-Hit w/ weapon",2,X,0,Unknown,Central,1300 W SUNSET BL,NaN,HOTEL,34.0685,-118.2460
1004891,240410786,11/10/2024,2330,14/10/2024,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD",NaN,Removes vict property,6,M,29,Black,Hollenbeck,1700 ALBION ST,NaN,RESTAURANT/FAST FOOD,34.0675,-118.2240
1004892,240309674,24/04/2024,1500,24/04/2024,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",STICK,"Stranger, Brandishes weapon, Hit-Hit w/ weapon, Suspect swung weapon, Put a weapon to body, Victim was aged (60 & over) or blind/physically disabled/unable to care for self",6,F,70,White,Southwest,FLOWER ST,JEFFERSON BL,SIDEWALK,34.0215,-118.2868
1004893,240910892,12/08/2024,2300,13/08/2024,VEHICLE - STOLEN,NaN,Unknown,6,NaN,0,NaN,Van Nuys,6900 VESPER AV,NaN,PARKING LOT,34.1961,-118.4510

In [21]:
# Rename the columns
crime.rename(columns={'DR_NO':'File ID',
                      'Date_Occured':'Date Occured',
                      'TIME OCC':'Time Occured',
                      'Date_Reported':'Date Reported',
                      'Crm Cd Desc':'Crime Description',
                      'Weapon Desc':'Weapon',
                      'Vict Sex':'Victim Sex',
                      'Vict Age':'Victim Age',
                      'Vict Descent':'Victim Descent',
                      'AREA NAME':'Area',
                      'LOCATION':'Location',
                      'Premis Desc':'Premis',
                      'LAT':'Latitude',
                      'LON':'Longitude'},
                       inplace=True)

C:\Users\omers\AppData\Local\Temp\ipykernel_3560\2899600642.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crime.rename(columns={'DR_NO':'File ID',

In [22]:
crime

,File ID,Date Occured,Time Occured,Date Reported,Crime Description,Weapon,Mocode Text,Severity Score,Victim Sex,Victim Age,Victim Descent,Area,Location,Cross Street,Premis,Latitude,Longitude
91235,200112035,21/05/2020,0525,21/05/2020,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)",ROCK/THROWN OBJECT,"Vandalized, Public Transit (Metrolink/Train Station,Metro Rail Red,Line Subway Station,, Suspect threw object at victim",1,NaN,0,NaN,Central,9TH,SPRING,MTA BUS,34.0420,-118.2555
133312,200116522,17/08/2020,0545,17/08/2020,VANDALISM - MISDEAMEANOR ($399 OR UNDER),"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)","Vandalized, Suspect is homeless/transient, Bodily Force",1,X,0,Unknown,Central,800 SANTEE ST,NaN,OTHER BUSINESS,34.0401,-118.2533
432358,221701255,08/12/2022,2138,08/12/2022,FAILURE TO YIELD,NaN,"Vehicle involved, Other MO (see rpt)",1,X,0,Unknown,Devonshire,AQUEDUCT AV,NORDHOFF ST,STREET,34.2249,-118.4792
495781,220509912,06/06/2022,2000,06/06/2022,TRESPASSING,NaN,"Suspect is homeless/transient, Suspect is Victim's Son",1,F,42,Hispanic/Latin/Mexican,Harbor,900 N FRIES AV,NaN,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",33.7815,-118.2650
508451,220805565,09/02/2022,0245,09/02/2022,TRESPASSING,NaN,Other MO (see rpt),1,F,21,Hispanic/Latin/Mexican,West LA,11700 WILSHIRE BL,NaN,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",34.0495,-118.4609
873827,230114706,22/06/2023,1550,22/06/2023,BATTERY POLICE (SIMPLE),UNKNOWN WEAPON/OTHER WEAPON,"LA Police Officer, Victim's Employment, Suspect threw object at victim, Suspect is homeless/transient",1,M,0,Hispanic/Latin/Mexican,Central,200 E 6TH ST,NaN,POLICE FACILITY,34.0448,-118.2474

In [23]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004894 entries, 0 to 1004893
Data columns (total 17 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   File ID            1004894 non-null  int64
 1   Date Occured       1004894 non-null  object
 2   Time Occured       1004894 non-null  object
 3   Date Reported      1004894 non-null  object
 4   Crime Description  1004894 non-null  object
 5   Weapon             327216 non-null   object
 6   Mocode Text        1004894 non-null  object
 7   Severity Score     1004894 non-null  int64
 8   Victim Sex         860263 non-null   object
 9   Victim Age         1004894 non-null  int64
 10  Victim Descent     860249 non-null   object
 11  Area               1004894 non-null  object
 12  Location           1004894 non-null  object
 13  Cross Street       154228 non-null   object
 14  Premis             1004306 non-null  object
 15  Latitude           1004894 non-null  float64
 16  Longitude          1004894 non-null  float64
dtypes: float64(2), int64(3), object(12)
memory usage: 130.3+ MB